changelogPath: CHANGELOG.md
language: en
categories:
  Features: ["feature", "feat", "enhancement"]
  Fixes: ["fix", "bug"]
  Docs: ["docs"]
  Performance: ["perf"]
  Refactor: ["refactor"]
  Tests: ["test"]
  Chores: ["chore"]
breakingLabels: ["breaking", "breaking-change", "major"]
monorepo:
  enabled: true
  detect: true
  packages:
    - "packages/*"
